name: Robot Framework Requests Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'results/**'  # Ignora alterações nos resultados dos testes
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-requests

    - name: Run Robot Framework tests
      run: |
        mkdir -p results
        robot --outputdir results project/tests/

    - name: Upload Robot Framework results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: results/
