name: Testar API com Robot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v3

      - name: Build e subir os containers da API
        run: docker-compose up -d --build

      - name: Aguardar API subir
        run: |
          echo "Esperando a API iniciar..."
          sleep 20  

      - name: Rodar testes Robot via Docker
        run: |
          docker run --rm \
            --network app-network \
            -v ${{ github.workspace }}/tests:/tests \
            ppodgorsek/robot-framework:latest \
            -v API_HOST:http://registerapi:8080 \
            /tests

      - name: Upload dos logs de teste
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-logs
          path: |
            log.html
            report.html
            output.xml
